### ISSUE TITLE
Home page hacked

### ISSUE THREAD

**Issue by lu-zero** [parasew/instiki#21]
Please clean it up

Current homepage:

> Installation is very easy, whether on MacOSX, Linux or Windows. The package includes a database (SQLite3) and webserver, so you’ll be up and running in minutes.
> 
> Keep up the good work, and post more articles like the one you have posted above. I’m quite sure I’ll learn many new stuff right here. Very interesting. Web Hosting Romania. Trustnet Solutions – Premium web hosting services, Brasov, Romania. Premium web hosting starting at just one euro per month, free domain registration. Stiu ca multora le plac vacantele reusite, adica sa fie cat mai frumos, comfortabil, distractie si daca se poate si preturi bune la cazare hajduszoboszlo asa ca va recomand linkul anterior. In Hajduszoboszlo exista cel mai mare parc de stranduri termale din estul Europei. Best way for learning how to tie a tie is the easy way, although it really helps to consult my guide. Don’t Make It Too Complicated If this sharp tie strategy doesn’t appeal to you, get a diagram and attempt a more sophisticated knot.  If you search for cleaning services Chicago I recommend Nikys, because he is one of my favorite cleaning services company in Chicago, Illinois, USA. Nikys cleaning services in Chicago Address: 4058 North Keystone Avenue #3, Chicago, IL, 60641, Phone: (773) 822-3618.

**Comment by l2dy** [comment]
>  Any link to `instiki.org` should (under present circumstances) be considered a bug.

The website linked on https://github.com/parasew/instiki is still `instiki.org`. Could you remove that?
