### ISSUE TITLE
Instiki Ruby 2.2 compatibility

### ISSUE THREAD

**Issue by hdiwan** [parasew/instiki#26]
The patch adds ruby-2.2 to the Gemfile to force iconv installation. 

diff --git a/Gemfile b/Gemfile
index ef043bb..ef64905 100644
--- a/Gemfile
+++ b/Gemfile
@@ -15,5 +15,5 @@ gem "rails_xss", "~> 0.4.0"
 gem "file_signature", "~> 1.2.0"
 gem "syntax", "~> 1.1.0"
 gem "maruku", :git => 'git://github.com/distler/maruku.git', :branch => 'nokogiri'
-gem 'iconv', :platforms => [:ruby_20, :ruby_21]
+gem 'iconv', :platforms => [:ruby_20, :ruby_21, :ruby_22]
 gem 'rdoc-data', :platforms => :ruby_18

**Comment by distler** [comment]
Thanks.
