### ISSUE TITLE
 3 easy Steps to get the Instiki experience

### ISSUE THREAD

**Issue by ThorsenRune** [parasew/instiki#27]
Well, maybe not so much. Now for 3 hrs I have struggled to install Ruby etc. so the statement is a bit exaggerated. 
Then at step 2 Run "instiki" I get a series of errors. 
Could you please make a sandbox somewhere so we can try before installing.

Thanks for the good work

**Comment by distler** [comment]
>Then at step 2 Run "instiki" I get a series of errors.

You'll need to be more specific, if you want there to be any *chance* of your errors getting fixed.

>Could you please make a sandbox somewhere so we can try before installing.

[Sandbox](https://golem.ph.utexas.edu/wiki/instiki/show/Sandbox).

**Comment by ThorsenRune** [comment]
On 22/06/2015 17:01, Jacques Distler wrote:
>
>     Then at step 2 Run "instiki" I get a series of errors.
>
> You'll need to be more specific, if you want there to be any /chance/ 
> of your errors getting fixed.
>
Installed Ruby (turning out to be 2.2)
following the steps.
trying all the different things
downgraded to ruby 2.1
same problem.

I'm not going to do more about it. The 'chuckle ...no step 3 ' made me 
go negative about the project  ;-)

>     Could you please make a sandbox somewhere so we can try before
>     installing.
>
> Sandbox <https://golem.ph.utexas.edu/wiki/instiki/show/Sandbox>.
>
Well in the sandbox it wasn't clear how to edit. However I see its not 
wysiwyg editing and that was what I was looking for.


---------------------
errors when launching:
Microsoft Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\xxxxxx>cd C:\temp\instiki-master

C:\temp\instiki-master>instiki

C:\temp\instiki-master>set 
PATH=.\lib\native\win32;C:\Ruby21-x64\bin;C:\ProgramD
ata\Oracle\Java\javapath;<deleted stuff>

C:\temp\instiki-master>ruby.exe script\server -e production
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/lib/bundler/dsl
.rb:232:in `block in _normalize_options': `ruby_22` is not a valid 
platform. The
  available options are: [:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, 
:mri, :m
ri_18, :mri_19, :mri_20, :mri_21, :rbx, :jruby, :jruby_18, :jruby_19, 
:mswin, :m
ingw, :mingw_18, :mingw_19, :mingw_20, :mingw_21, :x64_mingw, 
:x64_mingw_20, :x6
4_mingw_21] (Bundler::GemfileError)
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler/dsl.rb:230:in `each'
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler/dsl.rb:230:in `_normalize_options'
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler/dsl.rb:74:in `gem'
         from C:/temp/instiki-master/Gemfile:18:in `eval_gemfile'
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler/dsl.rb:30:in `instance_eval'
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler/dsl.rb:30:in `eval_gemfile'
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler/dsl.rb:9:in `evaluate'
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler/definition.rb:26:in `build'
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler.rb:152:in `definition'
         from 
C:/temp/instiki-master/vendor/plugins/bundler/gems/bundler-1.5.1/li
b/bundler.rb:115:in `setup'
         from C:/temp/instiki-master/config/preinitializer.rb:18:in 
`<top (requir
ed)>'
         from C:/temp/instiki-master/config/boot.rb:43:in `load'
         from C:/temp/instiki-master/config/boot.rb:43:in `preinitialize'
         from C:/temp/instiki-master/config/boot.rb:25:in `boot!'
         from C:/temp/instiki-master/config/boot.rb:139:in `<top 
(required)>'
         from 
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
         from 
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_req
uire.rb:54:in `require'
         from script/server:3:in `<main>'

C:\temp\instiki-master>

**Comment by distler** [comment]
The problem you encountered was introduced in [this commit](https://github.com/parasew/instiki/commit/09f550cb34168943b15d46329a89c14d54abb474) and fixed in [this one](https://github.com/parasew/instiki/commit/7e58d11247b210985df67ba2eb087395e34b31af). If you encounter another problem, please open an issue for it.
