### ISSUE TITLE
Youtube support and version 0.19.8

### ISSUE THREAD

**Issue by nzer0** [parasew/instiki#31]
I think the version 0.19.8 does not exist in github repo.

The documentation [here](https://golem.ph.utexas.edu/wiki/instiki/show/File+Uploads) says that instiki supports youtube embedding from version 0.19.8. It is strange though, because the instiki engine running the documentation site seems to be 0.19.7 as can be seen in the footer.

What am I missing? and how can I upgrade my instiki to the version 0.19.8?

**Comment by distler** [comment]
0.19.8 hasn't been released yet.

The current master on Github is very close to what the final release will be. And that is what the Instiki Documentation site is running. 

So, if you want Youtube support *now*, I would suggest grabbing the latest from Github and running that.
