### ISSUE TITLE
How to disable code section reformatting

### ISSUE THREAD

**Issue by BBQigniter** [parasew/instiki#40]
I use instiki for documenting some python stuff but I'm not happy about how code sections are reformatted by instiki. For example:

```
ListOfStrings(
              title = _("A List of some strings"),
              help  = _("A List of strings"),
              orientation = "horizontal"
              )
```

is reformatted to

```
ListOfStrings(
    title = _("A List of some strings"),
    help  = _("A List of strings"),
    orientation = "horizontal"
    )
```

Can someone tell me please where I'm able to disable that?

PS: Btw I tried to ask this question in the instiki forum, I signed up but never got the "activation"-mail and there is no resend option as far as I have seen.

**Comment by distler** [comment]
I'm [not seeing](https://golem.ph.utexas.edu/wiki/instiki/show/Sandbox#python) what you're seeing. Best as I can guess, you're using a proportional rather than a fixed-width font to display your code blocks. *Obviously* that won't give your the spacing you desire.

**Comment by distler** [comment]
As to the forum, dunno what happened with the email, but your account seems to be active.

**Comment by distler** [comment]
Did switching to a fixed-width font solve your problem?

**Comment by BBQigniter** [comment]
Sry, for the late answer. I hadn't time yet to try - I only had a quick look at the css and as far as I have seen a monospace-font is used and still somehow a few whitespaces are missing on the website but not if I go back to the editor.
I'll give more info asap - but this can take a while :(

**Comment by distler** [comment]
And are you using [fenced code blocks](https://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks) or the indented kind?
