### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by jarsp** [parasew/instiki#42]
Hi there,
I'm trying to get the Heroku deployment of Instiki to work. Following the instructions listed in the README gives an `ActiveRecord::AdapterNotSpecified: development database is not configured` error. I've tried modifying config/database.yml in various ways but I was unable to get it working. Is there any way that I can fix this?
Sorry for the trouble, I'm not that familiar with these tools. Thanks in advance.

**Comment by structuralist** [comment]
I had the same problem. Setting the `RAILS_ENV` environment variable to `production` fixed it. (It's under Settings > Config Variables.)

**Comment by jarsp** [comment]
Excellent, that worked! Thanks.
