### ISSUE TITLE
Oxford brackets

### ISSUE THREAD

**Issue by ayberkt** [parasew/instiki#45]
I've been looking for a way to get `stmaryrd`'s `\llbracket`, `\rrbacket` (⟦ ⟧) symbols with itex2MML but I have been unsuccessful so far. Am I missing something or is this not possible as of now? If it's not possible can we add a work-around to instiki? Thanks!

**Comment by distler** [comment]
I'll look into adding them to itex2MML, but I am afraid the results may not be satisfactory.

Right now, you can do ` $$\mathop{&#x301A;}\frac{A}{B}\mathop{&#x301B;}$$ `. But there's no way (as far as I can see) to make these symbols behave as stretchy delimiters in MathML. Which makes their usage somewhat less than satisfactory.

**Comment by distler** [comment]
These are supported, by default in itex2MML 1.5.8.
