### ISSUE TITLE
Spacing when typesetting $f:S \to T$

### ISSUE THREAD

**Issue by thielul** [parasew/instiki#50]
When I typeset $f:S \to T$ and view this in Safari the arrow is too close to T, same for $\mapsto$. In Chrome this looks fine, however. What is a bit strange now is that the same code in the [nLab](https://ncatlab.org/nlab/show/function) looks fine on Safari. Any ideas how to fix this?

**Comment by distler** [comment]
If I had to guess, what you are seeing is Safari's less-than-perfect [MathML rendering](https://golem.ph.utexas.edu/~distler/blog/archives/002926.html). In particular, I think it's [this bug](https://bugs.webkit.org/show_bug.cgi?id=170272). The nLab is using an outdated version of Instiki, which doesn't use Safari's native MathML rendering.

On balance, the advantages of the native rendering outway the disadvantages, but you should definitely report any MathML rendering bugs you encounter. That's the only way the Webkit people will be able to fixe them.

**Comment by thielul** [comment]
Yes, you're right, that's this bug probably. I'll post a follow-up.

**Comment by distler** [comment]
I believe this renders fine in the current Safari.
