### ISSUE TITLE
Search result page broken (not valid xml)

### ISSUE THREAD

**Issue by ilpssun** [parasew/instiki#57]
When I search anything in instiki that results in more than one hit, I get an error page.  For example, [searching for `git` in the official instiki](https://golem.ph.utexas.edu/wiki/instiki/search?query=git) results in a page that has a closing `</p>` without the opening tag:

```xhtml
<!-- ... -->
<ul>
      <li>
        <a href="/wiki/instiki/show/Browsers">Browsers</a>
      </li>
      <!-- ... -->
  </ul>

    <b>Create a new page, named:</b> "<span class='newWikiWord'><a href="/wiki/instiki/new/git">git</a></span>"
  </p>
<!-- ... -->
```

My browser displays an error page instead of the search results because it is not valid XML.

**Comment by distler** [comment]
Yikes. Who's in charge of QA around here? :-)

Fixed in [9749938](https://github.com/parasew/instiki/commit/974993846cddfd93913a62dcb368614ec4a865fd). Thank you!
