### ISSUE TITLE
Minor tweaks to improve page creation workflow

### ISSUE THREAD

**Issue by davidtanzer** [parasew/instiki#69]
1.  What is now called the search box could more accurately be called search/create as it is used for two distinct functions.   I suggest changing the ghost text in the search box to say "search/create" or "search or create".   That will help to orient a newcomer to the wiki world; it makes the interface self-documenting.     

2.  Suppose there is an article about the New York Mets, and there is only one article in the wiki which contains the word 'baseball.'    Now suppose that I want to create a page about baseball.   Currently, if I go to search/create and type in baseball, then the article on New York Mets is loaded, and I am not presented with any option to create a page called Baseball.  Besides not giving me what I was looking for, jumping to the New York Mets page feels arbitrary.  

The current rule is that if the search text matches a unique page, then that page is jumped to.   I suggest changing this rule so it only jumps to the page if the search text exactly matches the page title.   That is exactly the condition under which no page creation option should be presented.

**Comment by distler** [comment]
The current behaviour gently guides the user into the "correct" way to create a page called "baseball". That's *not* to take some action on the search page (which is *not* intended as a "search or create" page).

Rather, the user is taken to the "New York Mets" page, where he turns the word "baseball" into a WikiLink "[[baseball]]" and then clicks on that link to create the new page.

That way, the New York Mets page is correctly linked to the newly-created "baseball" page (which *wouldn't* happen in your scenario).

The only scenario in which creating the new page directly from the search page is the *correct* thing to do is if none of the existing pages talks about baseball at all. That's not quite the current behaviour: the current behaviour is to offer the option to create a new page if none of the existing pages have a *title* containing the work "baseball".

But that's close enough.

Now, you might object, "But what if the user doesn't know about WikiLink syntax?" To which I say, perhaps the user should familiarize herself with the rudiments of wiki syntax *before* creating her first page.

**Comment by davidtanzer** [comment]
Ok, I see the logic you are describing.   I will document it in my tutorial.   Thanks.

**Comment by distler** [comment]
To follow up a little more, the "desired" behaviour that I outlined does have its pitfalls.

In your example, say the user searched for "base" instead. This might still redirect to the "New York Mets" page (where it discusses Robinson Canó at second base). Trouble is, the user didn't mean "base" as in "second base"; she meant "base" as in "military base." So creating a WikiLink from the "New York Mets" page would be inappropriate.

The correct thing to do would be to refine the search, searching instead for "military base." *Then* she would be prompted to create a new page *with a proper, non-ambiguous name.*
