### ISSUE TITLE
Edit on Heroku deploy results in "undefinedundefined" on sub pages

### ISSUE THREAD

**Issue by jathayde** [parasew/instiki#75]
Not sure what is happening here. Heroku deploy based off the 07 Aug commit, and then following the deploy instructions. Imported content from an older version db. When I click on "edit" or try to create a new page, I end up with "undefinedundefined" as the contents of the textarea. Is this something that went wrong in porting the DB across?
<img width="1348" alt="Screen Shot 2021-02-15 at 11 04 52 AM" src="https://user-images.githubusercontent.com/2223/107969325-a3861280-6f7d-11eb-8c30-8d670d70a2c3.png">

**Comment by distler** [comment]
Is this related to [this bug](https://github.com/parasew/instiki/issues/56)? That was an incompatibility with a browser extension.

**Comment by jathayde** [comment]
That was it! It works as expected in a different browser without Grammarly installed.
